$id: http://example.com/example.json
type: object
definitions: {}
$schema: http://json-schema.org/draft-06/schema#
properties:
  from_topic:
    $id: /properties/from_topic
    type: string
    title: The From_topic Schema
    description: The kafkas topic this tranform module reads from
    examples:
    - raw
    enum:
    - raw
    - transformed
  to_source:
    $id: /properties/to_source
    type: object
    description: the source and all connection information needed
    properties:
      name:
        type: string
        description: the name of the source type the loader to will load data into
        examples:
        - local
    required:
    - name
  filter:
    $id: /properties/filter
    type: object
    title: Filter for Topic Messages
    description: json matching filter for kafka topic messages
    examples:
    - {state: {value: true}} # matches only messages
required:
- from_topic
- to_source