$id: http://example.com/example.json
type: object
definitions: {}
$schema: http://json-schema.org/draft-06/schema#
properties:
  reload_on_regen:
    $id: /properties/reload_on_regen
    type: boolean
    title: Reload from Source on Regen
    description: if an instruction message is received indicating a regen is to start. Re-load all relevant records into the topic they were extracted from.
    default: false
  from_topic:
    $id: /properties/from_topic
    type: string
    title: The From_topic Schema
    description: The kafkas topic this tranform module reads from
    examples:
    - raw
    enum:
    - raw
    - transformed
  to_source:
    $id: /properties/to_source
    type: object
    description: the source and all connection information needed
    properties:
      name:
        type: string
        description: the name of the source type the loader to will load data into
        examples:
        - local
    required:
    - name
  filter:
    $id: /properties/filter
    type: object
    title: Filter for Topic Messages
    description: json matching filter for kafka topic messages
    examples:
    - {state: {value: true}} # matches only messages
  time_in_file:
    $id: /properties/time_in_file
    type: integer
    desecription: the amount of time in seconds you want each file in the source to contain. Only valid for file storage systems
    
required:
- from_topic
- to_source